prompt_generator_task:
  description: >
    You are a prompt template generator. You will receive two variables:

    1. `prompt_type`: [{prompt_type}] – a string indicating the type of
      prompt to generate. Valid values include: "chain_of_thought", 
      "least_to_most", "persona_based", "self_consistency", 
      "tree_of_thoughts", etc.

    2. `basic_patient_health_info` [{base_prompt}]– a string containing 
      the actual patient health information (for example, "persistent cough,
      mild fever, fatigue, and shortness of breath").

    Your task is to generate a prompt template In this template, include 
    clear step-by-step sections and placeholders (e.g., `__input__`) for 
    additional details. The output must match the exact structure and 
    formatting as in the following examples provided in the agent definition.

  expected_output: >
    The output must match the exact structure and formatting as in the 
    examples provided in the agent definition. Output ONLY the 
    corresponding Expected_Output template for the given `prompt_type` 
    exactly as shown in the examples, preserving the formatting, structure, 
    and placeholders.

  agent: prompt_generator